#!/bin/bash

readonly ZEROARG=$0
INFILE=""
OUTFILE_ATOM_SCORES=""
OUTFILE_RESIDUE_SCORES=""
OUTFILE_CAMEO_RESIDUE_SCORES=""
SMOOTHING_WINDOW="5"
HELP_MODE=false

while getopts "i:a:r:c:s:h" OPTION
do
	case $OPTION in
	i)
		INFILE=$OPTARG
		;;
	a)
		OUTFILE_ATOM_SCORES=$OPTARG
		;;
	r)
		OUTFILE_RESIDUE_SCORES=$OPTARG
		;;
	c)
		OUTFILE_CAMEO_RESIDUE_SCORES=$OPTARG
		;;
	s)
		SMOOTHING_WINDOW=$OPTARG
		;;
	h)
		HELP_MODE=true
		;;
	esac
done

if [ -z "$INFILE" ] || $HELP_MODE
then
cat >&2 << EOF
Script parameters:
    -i input_file.pdb
    [-a output_atom_scores_file]
    [-r output_residue_scores_file]
    [-s residue_scores_smoothing_window_size]
EOF
exit 1
fi

if [[ $ZEROARG == *"/"* ]]
then
	cd $(dirname $ZEROARG)
	export PATH=$(pwd):$PATH
	cd - &> /dev/null
fi

command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }

if [ ! -s "$INFILE" ]
then
	echo >&2 "Error: input file does not exist or is empty"
	exit 1
fi

readonly TMPDIR=$(mktemp -d)
trap "rm -r $TMPDIR" EXIT

INPRINTER="cat"
file $INFILE > $TMPDIR/input_file_type
if grep "gzip compressed data" $TMPDIR/input_file_type > /dev/null
then
	INPRINTER="zcat"
fi
$INPRINTER $INFILE > $TMPDIR/extracted_input_file

cat $TMPDIR/extracted_input_file \
| voronota get-balls-from-atoms-file \
  --annotated \
  --radii-file <(voronota-resources radii) \
| voronota query-balls \
  --drop-adjuncts \
  --drop-altloc-indicators \
| tee $TMPDIR/balls \
| voronota calculate-contacts \
  --annotated \
  --tag-centrality \
| voronota query-contacts \
  --match-min-seq-sep 1 \
| voronota query-contacts \
  --match-first 'A<C>' \
  --match-second 'A<N>' \
  --match-max-seq-sep 1 \
  --match-max-dist 1.6 \
  --invert \
| voronota query-contacts \
  --match-min-seq-sep 1 \
  --match-max-seq-sep 1 \
  --set-tags 'sep1' \
| voronota query-contacts \
  --match-min-seq-sep 2 \
  --no-solvent \
  --set-tags 'sep2' \
| awk '{print $1 " " $2 " " $5 " " $3}' \
| tr ';' '_' \
| tee $TMPDIR/contacts \
| voronota score-contacts-energy \
  --potential-file <(voronota-resources energy_potential) \
  --atom-scores-file $TMPDIR/atom_energies \
> /dev/null

cat $TMPDIR/contacts \
| voronota query-contacts-depth-values \
> $TMPDIR/depth_values

cat $TMPDIR/atom_energies \
| voronota score-contacts-quality \
  --default-mean -0.34 \
  --default-sd 0.19 \
  --means-and-sds-file <(voronota-resources energy_means_and_sds) \
  --external-weights-file $TMPDIR/depth_values \
  --smoothing-window $SMOOTHING_WINDOW \
  --atom-scores-file $TMPDIR/atom_quality_scores \
  --residue-scores-file $TMPDIR/residue_quality_scores \
> $TMPDIR/global_quality_score

if [ -n "$OUTFILE_ATOM_SCORES" ]
then
	mkdir -p $(dirname $OUTFILE_ATOM_SCORES)
	cp $TMPDIR/atom_quality_scores "$OUTFILE_ATOM_SCORES"
fi

if [ -n "$OUTFILE_RESIDUE_SCORES" ]
then
	mkdir -p $(dirname $OUTFILE_RESIDUE_SCORES)
	cp $TMPDIR/residue_quality_scores "$OUTFILE_RESIDUE_SCORES"
fi

if [ -n "$OUTFILE_CAMEO_RESIDUE_SCORES" ]
then
	mkdir -p $(dirname $OUTFILE_CAMEO_RESIDUE_SCORES)
	cat $TMPDIR/balls \
	| voronota query-balls \
	  --set-external-adjuncts <(awk '{print $1 " " (10*(1-$2))}' $TMPDIR/residue_quality_scores) \
	  --set-external-adjuncts-name rqscore \
	| voronota write-balls-to-atoms-file \
	  --pdb-output $OUTFILE_CAMEO_RESIDUE_SCORES \
	  --pdb-output-b-factor rqscore \
	  --pdb-output-template $TMPDIR/extracted_input_file \
	> /dev/null
fi

echo $INFILE $(cat $TMPDIR/global_quality_score)
