#!/bin/bash

#
# Non-interactive execution example:
#    voronota-runscript arg1 arg2 arg3 < ./script.bash
#
# Interactive execution example:
#    bash --init-file ./voronota-runscript
#

NONINTERACTIVE=true

if [ -t 0 ]
then
	NONINTERACTIVE=false
fi

if $NONINTERACTIVE
then
	ZEROARG=$0
	ALLARGS=("$@")
	if [[ "$ZEROARG" == *"/"* ]]
	then
		cd $(dirname $ZEROARG)
		export PATH=$(pwd):$PATH
		cd - &> /dev/null
	fi
fi

command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }

coproc VORONOTA_PROC { voronota x-run-script --interactive --max-unfolding 0; }
exec 5<&${VORONOTA_PROC[0]} 6>&${VORONOTA_PROC[1]}

readonly VORONOTA_PROC_TMPDIR="$(mktemp -d)"

function exit_environment
{
	exec 5<&- 6>&-
	rm -r "$VORONOTA_PROC_TMPDIR"
}

trap exit_environment EXIT

function vc
{
	echo "$*" >&6
	read VORONOTAOUT <&5
	echo "$VORONOTAOUT"
	unset VORONOTAOUT
}

function vcq
{
	vc "$*" > /dev/null
}

voronota-resources radii > "$VORONOTA_PROC_TMPDIR/_radii"
voronota-resources voromqa_v1_energy_potential > "$VORONOTA_PROC_TMPDIR/_voromqa_v1_energy_potential"
voronota-resources voromqa_v1_energy_means_and_sds > "$VORONOTA_PROC_TMPDIR/_voromqa_v1_energy_means_and_sds"
vc "setup-loading --radii-file '$VORONOTA_PROC_TMPDIR/_radii'"
vc "setup-voromqa --potential '$VORONOTA_PROC_TMPDIR/_voromqa_v1_energy_potential' --means-and-sds '$VORONOTA_PROC_TMPDIR/_voromqa_v1_energy_means_and_sds'"

if $NONINTERACTIVE
then
	SCRIPTFILE="$VORONOTA_PROC_TMPDIR/_script.bash"
	cat | egrep -v '^#' > "$SCRIPTFILE"
	chmod +x "$SCRIPTFILE"
	export VORONOTA_PROC_TMPDIR
	export -f vc
	export -f vcq
	$SCRIPTFILE "${ALLARGS[@]}"
fi

