#!/bin/bash

readonly ZEROARG=$0
INPUT_PDB_FILE=""
INPUT_SCORES_FILE=""
MULTIPLE_MODELS_CHAINS_OPTION=""
HELP_MODE=false

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	-p)
		INPUT_PDB_FILE="$OPTARG"
		shift
		;;
	-s)
		INPUT_SCORES_FILE="$OPTARG"
		shift
		;;
	-q)
		MULTIPLE_MODELS_CHAINS_OPTION="--multimodel-chains"
		;;
	-h)
		HELP_MODE=true
		;;
	esac
done

if [ -z "$INPUT_PDB_FILE" ] || [ -z "$INPUT_SCORES_FILE" ] || $HELP_MODE
then
cat >&2 << EOF
Script parameters:
    -p input_structure_file.pdb
    -s input_scores_file
EOF
exit 1
fi

if [[ $ZEROARG == *"/"* ]]
then
	cd $(dirname $ZEROARG)
	export PATH=$(pwd):$PATH
	cd - &> /dev/null
fi

command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }

if [ ! -s "$INPUT_PDB_FILE" ]
then
	echo >&2 "Error: input structure file does not exist or is empty"
	exit 1
fi

if [ ! -s "$INPUT_SCORES_FILE" ]
then
	echo >&2 "Error: input scores file does not exist or is empty"
	exit 1
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

cat $INPUT_PDB_FILE \
| voronota get-balls-from-atoms-file \
  --annotated $MULTIPLE_MODELS_CHAINS_OPTION \
  --include-heteroatoms \
| voronota query-balls \
  --drop-altloc-indicators \
  --set-external-adjuncts $INPUT_SCORES_FILE \
  --set-external-adjuncts-name score \
| voronota x-write-balls-to-atoms-file \
  --pdb-output $TMPLDIR/result \
  --pdb-output-b-factor score \
> /dev/null

cat $TMPLDIR/result
