# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _cadscorelt_python
else:
    import _cadscorelt_python

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _cadscorelt_python.delete_SwigPyIterator

    def value(self):
        return _cadscorelt_python.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _cadscorelt_python.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _cadscorelt_python.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _cadscorelt_python.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _cadscorelt_python.SwigPyIterator_equal(self, x)

    def copy(self):
        return _cadscorelt_python.SwigPyIterator_copy(self)

    def next(self):
        return _cadscorelt_python.SwigPyIterator_next(self)

    def __next__(self):
        return _cadscorelt_python.SwigPyIterator___next__(self)

    def previous(self):
        return _cadscorelt_python.SwigPyIterator_previous(self)

    def advance(self, n):
        return _cadscorelt_python.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _cadscorelt_python.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _cadscorelt_python.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _cadscorelt_python.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _cadscorelt_python.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _cadscorelt_python.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _cadscorelt_python.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _cadscorelt_python:
_cadscorelt_python.SwigPyIterator_swigregister(SwigPyIterator)
class VectorInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorInt___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorInt___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorInt___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorInt___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorInt_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorInt_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorInt_empty(self)

    def size(self):
        return _cadscorelt_python.VectorInt_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorInt_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorInt_begin(self)

    def end(self):
        return _cadscorelt_python.VectorInt_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorInt_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorInt_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorInt_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorInt_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorInt_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorInt_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorInt_swiginit(self, _cadscorelt_python.new_VectorInt(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorInt_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorInt_front(self)

    def back(self):
        return _cadscorelt_python.VectorInt_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorInt_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorInt_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorInt_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorInt_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorInt_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorInt

# Register VectorInt in _cadscorelt_python:
_cadscorelt_python.VectorInt_swigregister(VectorInt)
class VectorMolecularAtomBall(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorMolecularAtomBall_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorMolecularAtomBall___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorMolecularAtomBall___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorMolecularAtomBall___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorMolecularAtomBall___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorMolecularAtomBall___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorMolecularAtomBall___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorMolecularAtomBall___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorMolecularAtomBall___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorMolecularAtomBall___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorMolecularAtomBall_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorMolecularAtomBall_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorMolecularAtomBall_empty(self)

    def size(self):
        return _cadscorelt_python.VectorMolecularAtomBall_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorMolecularAtomBall_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorMolecularAtomBall_begin(self)

    def end(self):
        return _cadscorelt_python.VectorMolecularAtomBall_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorMolecularAtomBall_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorMolecularAtomBall_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorMolecularAtomBall_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorMolecularAtomBall_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorMolecularAtomBall_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorMolecularAtomBall_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorMolecularAtomBall_swiginit(self, _cadscorelt_python.new_VectorMolecularAtomBall(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorMolecularAtomBall_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorMolecularAtomBall_front(self)

    def back(self):
        return _cadscorelt_python.VectorMolecularAtomBall_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorMolecularAtomBall_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorMolecularAtomBall_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorMolecularAtomBall_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorMolecularAtomBall_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorMolecularAtomBall_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorMolecularAtomBall

# Register VectorMolecularAtomBall in _cadscorelt_python:
_cadscorelt_python.VectorMolecularAtomBall_swigregister(VectorMolecularAtomBall)
class VectorStructureDescriptor(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorStructureDescriptor_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorStructureDescriptor___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorStructureDescriptor___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorStructureDescriptor___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorStructureDescriptor___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorStructureDescriptor___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorStructureDescriptor___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorStructureDescriptor___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorStructureDescriptor___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorStructureDescriptor___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorStructureDescriptor_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorStructureDescriptor_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorStructureDescriptor_empty(self)

    def size(self):
        return _cadscorelt_python.VectorStructureDescriptor_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorStructureDescriptor_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorStructureDescriptor_begin(self)

    def end(self):
        return _cadscorelt_python.VectorStructureDescriptor_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorStructureDescriptor_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorStructureDescriptor_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorStructureDescriptor_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorStructureDescriptor_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorStructureDescriptor_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorStructureDescriptor_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorStructureDescriptor_swiginit(self, _cadscorelt_python.new_VectorStructureDescriptor(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorStructureDescriptor_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorStructureDescriptor_front(self)

    def back(self):
        return _cadscorelt_python.VectorStructureDescriptor_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorStructureDescriptor_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorStructureDescriptor_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorStructureDescriptor_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorStructureDescriptor_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorStructureDescriptor_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorStructureDescriptor

# Register VectorStructureDescriptor in _cadscorelt_python:
_cadscorelt_python.VectorStructureDescriptor_swigregister(VectorStructureDescriptor)
class VectorGlobalScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorGlobalScore_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorGlobalScore___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorGlobalScore___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorGlobalScore___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorGlobalScore___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorGlobalScore___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorGlobalScore___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorGlobalScore___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorGlobalScore___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorGlobalScore___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorGlobalScore_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorGlobalScore_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorGlobalScore_empty(self)

    def size(self):
        return _cadscorelt_python.VectorGlobalScore_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorGlobalScore_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorGlobalScore_begin(self)

    def end(self):
        return _cadscorelt_python.VectorGlobalScore_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorGlobalScore_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorGlobalScore_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorGlobalScore_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorGlobalScore_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorGlobalScore_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorGlobalScore_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorGlobalScore_swiginit(self, _cadscorelt_python.new_VectorGlobalScore(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorGlobalScore_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorGlobalScore_front(self)

    def back(self):
        return _cadscorelt_python.VectorGlobalScore_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorGlobalScore_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorGlobalScore_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorGlobalScore_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorGlobalScore_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorGlobalScore_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorGlobalScore

# Register VectorGlobalScore in _cadscorelt_python:
_cadscorelt_python.VectorGlobalScore_swigregister(VectorGlobalScore)
class VectorAtomScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorAtomScore_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorAtomScore___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorAtomScore___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorAtomScore___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorAtomScore___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorAtomScore___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorAtomScore___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorAtomScore___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorAtomScore___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorAtomScore___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorAtomScore_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorAtomScore_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorAtomScore_empty(self)

    def size(self):
        return _cadscorelt_python.VectorAtomScore_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorAtomScore_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorAtomScore_begin(self)

    def end(self):
        return _cadscorelt_python.VectorAtomScore_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorAtomScore_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorAtomScore_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorAtomScore_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorAtomScore_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorAtomScore_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorAtomScore_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorAtomScore_swiginit(self, _cadscorelt_python.new_VectorAtomScore(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorAtomScore_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorAtomScore_front(self)

    def back(self):
        return _cadscorelt_python.VectorAtomScore_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorAtomScore_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorAtomScore_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorAtomScore_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorAtomScore_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorAtomScore_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorAtomScore

# Register VectorAtomScore in _cadscorelt_python:
_cadscorelt_python.VectorAtomScore_swigregister(VectorAtomScore)
class VectorResidueScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorResidueScore_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorResidueScore___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorResidueScore___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorResidueScore___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorResidueScore___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorResidueScore___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorResidueScore___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorResidueScore___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorResidueScore___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorResidueScore___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorResidueScore_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorResidueScore_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorResidueScore_empty(self)

    def size(self):
        return _cadscorelt_python.VectorResidueScore_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorResidueScore_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorResidueScore_begin(self)

    def end(self):
        return _cadscorelt_python.VectorResidueScore_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorResidueScore_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorResidueScore_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorResidueScore_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorResidueScore_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorResidueScore_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorResidueScore_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorResidueScore_swiginit(self, _cadscorelt_python.new_VectorResidueScore(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorResidueScore_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorResidueScore_front(self)

    def back(self):
        return _cadscorelt_python.VectorResidueScore_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorResidueScore_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorResidueScore_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorResidueScore_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorResidueScore_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorResidueScore_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorResidueScore

# Register VectorResidueScore in _cadscorelt_python:
_cadscorelt_python.VectorResidueScore_swigregister(VectorResidueScore)
class VectorChainScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorChainScore_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorChainScore___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorChainScore___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorChainScore___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorChainScore___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorChainScore___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorChainScore___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorChainScore___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorChainScore___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorChainScore___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorChainScore_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorChainScore_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorChainScore_empty(self)

    def size(self):
        return _cadscorelt_python.VectorChainScore_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorChainScore_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorChainScore_begin(self)

    def end(self):
        return _cadscorelt_python.VectorChainScore_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorChainScore_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorChainScore_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorChainScore_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorChainScore_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorChainScore_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorChainScore_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorChainScore_swiginit(self, _cadscorelt_python.new_VectorChainScore(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorChainScore_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorChainScore_front(self)

    def back(self):
        return _cadscorelt_python.VectorChainScore_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorChainScore_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorChainScore_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorChainScore_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorChainScore_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorChainScore_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorChainScore

# Register VectorChainScore in _cadscorelt_python:
_cadscorelt_python.VectorChainScore_swigregister(VectorChainScore)
class VectorAtomAtomScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorAtomAtomScore_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorAtomAtomScore___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorAtomAtomScore___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorAtomAtomScore___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorAtomAtomScore___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorAtomAtomScore___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorAtomAtomScore___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorAtomAtomScore___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorAtomAtomScore___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorAtomAtomScore___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorAtomAtomScore_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorAtomAtomScore_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorAtomAtomScore_empty(self)

    def size(self):
        return _cadscorelt_python.VectorAtomAtomScore_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorAtomAtomScore_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorAtomAtomScore_begin(self)

    def end(self):
        return _cadscorelt_python.VectorAtomAtomScore_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorAtomAtomScore_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorAtomAtomScore_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorAtomAtomScore_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorAtomAtomScore_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorAtomAtomScore_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorAtomAtomScore_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorAtomAtomScore_swiginit(self, _cadscorelt_python.new_VectorAtomAtomScore(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorAtomAtomScore_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorAtomAtomScore_front(self)

    def back(self):
        return _cadscorelt_python.VectorAtomAtomScore_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorAtomAtomScore_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorAtomAtomScore_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorAtomAtomScore_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorAtomAtomScore_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorAtomAtomScore_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorAtomAtomScore

# Register VectorAtomAtomScore in _cadscorelt_python:
_cadscorelt_python.VectorAtomAtomScore_swigregister(VectorAtomAtomScore)
class VectorResidueResidueScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorResidueResidueScore_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorResidueResidueScore___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorResidueResidueScore___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorResidueResidueScore___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorResidueResidueScore___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorResidueResidueScore___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorResidueResidueScore___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorResidueResidueScore___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorResidueResidueScore___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorResidueResidueScore___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorResidueResidueScore_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorResidueResidueScore_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorResidueResidueScore_empty(self)

    def size(self):
        return _cadscorelt_python.VectorResidueResidueScore_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorResidueResidueScore_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorResidueResidueScore_begin(self)

    def end(self):
        return _cadscorelt_python.VectorResidueResidueScore_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorResidueResidueScore_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorResidueResidueScore_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorResidueResidueScore_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorResidueResidueScore_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorResidueResidueScore_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorResidueResidueScore_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorResidueResidueScore_swiginit(self, _cadscorelt_python.new_VectorResidueResidueScore(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorResidueResidueScore_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorResidueResidueScore_front(self)

    def back(self):
        return _cadscorelt_python.VectorResidueResidueScore_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorResidueResidueScore_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorResidueResidueScore_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorResidueResidueScore_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorResidueResidueScore_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorResidueResidueScore_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorResidueResidueScore

# Register VectorResidueResidueScore in _cadscorelt_python:
_cadscorelt_python.VectorResidueResidueScore_swigregister(VectorResidueResidueScore)
class VectorChainChainScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cadscorelt_python.VectorChainChainScore_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cadscorelt_python.VectorChainChainScore___nonzero__(self)

    def __bool__(self):
        return _cadscorelt_python.VectorChainChainScore___bool__(self)

    def __len__(self):
        return _cadscorelt_python.VectorChainChainScore___len__(self)

    def __getslice__(self, i, j):
        return _cadscorelt_python.VectorChainChainScore___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cadscorelt_python.VectorChainChainScore___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cadscorelt_python.VectorChainChainScore___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cadscorelt_python.VectorChainChainScore___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cadscorelt_python.VectorChainChainScore___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cadscorelt_python.VectorChainChainScore___setitem__(self, *args)

    def pop(self):
        return _cadscorelt_python.VectorChainChainScore_pop(self)

    def append(self, x):
        return _cadscorelt_python.VectorChainChainScore_append(self, x)

    def empty(self):
        return _cadscorelt_python.VectorChainChainScore_empty(self)

    def size(self):
        return _cadscorelt_python.VectorChainChainScore_size(self)

    def swap(self, v):
        return _cadscorelt_python.VectorChainChainScore_swap(self, v)

    def begin(self):
        return _cadscorelt_python.VectorChainChainScore_begin(self)

    def end(self):
        return _cadscorelt_python.VectorChainChainScore_end(self)

    def rbegin(self):
        return _cadscorelt_python.VectorChainChainScore_rbegin(self)

    def rend(self):
        return _cadscorelt_python.VectorChainChainScore_rend(self)

    def clear(self):
        return _cadscorelt_python.VectorChainChainScore_clear(self)

    def get_allocator(self):
        return _cadscorelt_python.VectorChainChainScore_get_allocator(self)

    def pop_back(self):
        return _cadscorelt_python.VectorChainChainScore_pop_back(self)

    def erase(self, *args):
        return _cadscorelt_python.VectorChainChainScore_erase(self, *args)

    def __init__(self, *args):
        _cadscorelt_python.VectorChainChainScore_swiginit(self, _cadscorelt_python.new_VectorChainChainScore(*args))

    def push_back(self, x):
        return _cadscorelt_python.VectorChainChainScore_push_back(self, x)

    def front(self):
        return _cadscorelt_python.VectorChainChainScore_front(self)

    def back(self):
        return _cadscorelt_python.VectorChainChainScore_back(self)

    def assign(self, n, x):
        return _cadscorelt_python.VectorChainChainScore_assign(self, n, x)

    def resize(self, *args):
        return _cadscorelt_python.VectorChainChainScore_resize(self, *args)

    def insert(self, *args):
        return _cadscorelt_python.VectorChainChainScore_insert(self, *args)

    def reserve(self, n):
        return _cadscorelt_python.VectorChainChainScore_reserve(self, n)

    def capacity(self):
        return _cadscorelt_python.VectorChainChainScore_capacity(self)
    __swig_destroy__ = _cadscorelt_python.delete_VectorChainChainScore

# Register VectorChainChainScore in _cadscorelt_python:
_cadscorelt_python.VectorChainChainScore_swigregister(VectorChainChainScore)
class MolecularAtomBall(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ID_chain = property(_cadscorelt_python.MolecularAtomBall_ID_chain_get, _cadscorelt_python.MolecularAtomBall_ID_chain_set)
    ID_residue_seq_number = property(_cadscorelt_python.MolecularAtomBall_ID_residue_seq_number_get, _cadscorelt_python.MolecularAtomBall_ID_residue_seq_number_set)
    ID_residue_icode = property(_cadscorelt_python.MolecularAtomBall_ID_residue_icode_get, _cadscorelt_python.MolecularAtomBall_ID_residue_icode_set)
    ID_atom_name = property(_cadscorelt_python.MolecularAtomBall_ID_atom_name_get, _cadscorelt_python.MolecularAtomBall_ID_atom_name_set)
    residue_name = property(_cadscorelt_python.MolecularAtomBall_residue_name_get, _cadscorelt_python.MolecularAtomBall_residue_name_set)
    element = property(_cadscorelt_python.MolecularAtomBall_element_get, _cadscorelt_python.MolecularAtomBall_element_set)
    x = property(_cadscorelt_python.MolecularAtomBall_x_get, _cadscorelt_python.MolecularAtomBall_x_set)
    y = property(_cadscorelt_python.MolecularAtomBall_y_get, _cadscorelt_python.MolecularAtomBall_y_set)
    z = property(_cadscorelt_python.MolecularAtomBall_z_get, _cadscorelt_python.MolecularAtomBall_z_set)
    r = property(_cadscorelt_python.MolecularAtomBall_r_get, _cadscorelt_python.MolecularAtomBall_r_set)

    def __init__(self, *args):
        _cadscorelt_python.MolecularAtomBall_swiginit(self, _cadscorelt_python.new_MolecularAtomBall(*args))
    __swig_destroy__ = _cadscorelt_python.delete_MolecularAtomBall

# Register MolecularAtomBall in _cadscorelt_python:
_cadscorelt_python.MolecularAtomBall_swigregister(MolecularAtomBall)
class StructureDescriptor(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_cadscorelt_python.StructureDescriptor_name_get, _cadscorelt_python.StructureDescriptor_name_set)
    is_target = property(_cadscorelt_python.StructureDescriptor_is_target_get, _cadscorelt_python.StructureDescriptor_is_target_set)
    is_model = property(_cadscorelt_python.StructureDescriptor_is_model_get, _cadscorelt_python.StructureDescriptor_is_model_set)
    renaming_of_chains = property(_cadscorelt_python.StructureDescriptor_renaming_of_chains_get, _cadscorelt_python.StructureDescriptor_renaming_of_chains_set)
    reference_alignment_info = property(_cadscorelt_python.StructureDescriptor_reference_alignment_info_get, _cadscorelt_python.StructureDescriptor_reference_alignment_info_set)

    def __init__(self):
        _cadscorelt_python.StructureDescriptor_swiginit(self, _cadscorelt_python.new_StructureDescriptor())
    __swig_destroy__ = _cadscorelt_python.delete_StructureDescriptor

# Register StructureDescriptor in _cadscorelt_python:
_cadscorelt_python.StructureDescriptor_swigregister(StructureDescriptor)
class GlobalScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    target_name = property(_cadscorelt_python.GlobalScore_target_name_get, _cadscorelt_python.GlobalScore_target_name_set)
    model_name = property(_cadscorelt_python.GlobalScore_model_name_get, _cadscorelt_python.GlobalScore_model_name_set)
    renaming_of_model_chains = property(_cadscorelt_python.GlobalScore_renaming_of_model_chains_get, _cadscorelt_python.GlobalScore_renaming_of_model_chains_set)
    cadscore = property(_cadscorelt_python.GlobalScore_cadscore_get, _cadscorelt_python.GlobalScore_cadscore_set)
    F1_of_areas = property(_cadscorelt_python.GlobalScore_F1_of_areas_get, _cadscorelt_python.GlobalScore_F1_of_areas_set)
    target_area = property(_cadscorelt_python.GlobalScore_target_area_get, _cadscorelt_python.GlobalScore_target_area_set)
    model_area = property(_cadscorelt_python.GlobalScore_model_area_get, _cadscorelt_python.GlobalScore_model_area_set)
    TP_area = property(_cadscorelt_python.GlobalScore_TP_area_get, _cadscorelt_python.GlobalScore_TP_area_set)
    FP_area = property(_cadscorelt_python.GlobalScore_FP_area_get, _cadscorelt_python.GlobalScore_FP_area_set)
    FN_area = property(_cadscorelt_python.GlobalScore_FN_area_get, _cadscorelt_python.GlobalScore_FN_area_set)

    def __init__(self):
        _cadscorelt_python.GlobalScore_swiginit(self, _cadscorelt_python.new_GlobalScore())
    __swig_destroy__ = _cadscorelt_python.delete_GlobalScore

# Register GlobalScore in _cadscorelt_python:
_cadscorelt_python.GlobalScore_swigregister(GlobalScore)
class AtomScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ID_chain = property(_cadscorelt_python.AtomScore_ID_chain_get, _cadscorelt_python.AtomScore_ID_chain_set)
    ID_residue_seq_number = property(_cadscorelt_python.AtomScore_ID_residue_seq_number_get, _cadscorelt_python.AtomScore_ID_residue_seq_number_set)
    ID_residue_icode = property(_cadscorelt_python.AtomScore_ID_residue_icode_get, _cadscorelt_python.AtomScore_ID_residue_icode_set)
    ID_atom_name = property(_cadscorelt_python.AtomScore_ID_atom_name_get, _cadscorelt_python.AtomScore_ID_atom_name_set)
    cadscore = property(_cadscorelt_python.AtomScore_cadscore_get, _cadscorelt_python.AtomScore_cadscore_set)
    F1_of_areas = property(_cadscorelt_python.AtomScore_F1_of_areas_get, _cadscorelt_python.AtomScore_F1_of_areas_set)
    target_area = property(_cadscorelt_python.AtomScore_target_area_get, _cadscorelt_python.AtomScore_target_area_set)
    model_area = property(_cadscorelt_python.AtomScore_model_area_get, _cadscorelt_python.AtomScore_model_area_set)
    TP_area = property(_cadscorelt_python.AtomScore_TP_area_get, _cadscorelt_python.AtomScore_TP_area_set)
    FP_area = property(_cadscorelt_python.AtomScore_FP_area_get, _cadscorelt_python.AtomScore_FP_area_set)
    FN_area = property(_cadscorelt_python.AtomScore_FN_area_get, _cadscorelt_python.AtomScore_FN_area_set)

    def __init__(self):
        _cadscorelt_python.AtomScore_swiginit(self, _cadscorelt_python.new_AtomScore())
    __swig_destroy__ = _cadscorelt_python.delete_AtomScore

# Register AtomScore in _cadscorelt_python:
_cadscorelt_python.AtomScore_swigregister(AtomScore)
class ResidueScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ID_chain = property(_cadscorelt_python.ResidueScore_ID_chain_get, _cadscorelt_python.ResidueScore_ID_chain_set)
    ID_residue_seq_number = property(_cadscorelt_python.ResidueScore_ID_residue_seq_number_get, _cadscorelt_python.ResidueScore_ID_residue_seq_number_set)
    ID_residue_icode = property(_cadscorelt_python.ResidueScore_ID_residue_icode_get, _cadscorelt_python.ResidueScore_ID_residue_icode_set)
    cadscore = property(_cadscorelt_python.ResidueScore_cadscore_get, _cadscorelt_python.ResidueScore_cadscore_set)
    F1_of_areas = property(_cadscorelt_python.ResidueScore_F1_of_areas_get, _cadscorelt_python.ResidueScore_F1_of_areas_set)
    target_area = property(_cadscorelt_python.ResidueScore_target_area_get, _cadscorelt_python.ResidueScore_target_area_set)
    model_area = property(_cadscorelt_python.ResidueScore_model_area_get, _cadscorelt_python.ResidueScore_model_area_set)
    TP_area = property(_cadscorelt_python.ResidueScore_TP_area_get, _cadscorelt_python.ResidueScore_TP_area_set)
    FP_area = property(_cadscorelt_python.ResidueScore_FP_area_get, _cadscorelt_python.ResidueScore_FP_area_set)
    FN_area = property(_cadscorelt_python.ResidueScore_FN_area_get, _cadscorelt_python.ResidueScore_FN_area_set)

    def __init__(self):
        _cadscorelt_python.ResidueScore_swiginit(self, _cadscorelt_python.new_ResidueScore())
    __swig_destroy__ = _cadscorelt_python.delete_ResidueScore

# Register ResidueScore in _cadscorelt_python:
_cadscorelt_python.ResidueScore_swigregister(ResidueScore)
class ChainScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ID_chain = property(_cadscorelt_python.ChainScore_ID_chain_get, _cadscorelt_python.ChainScore_ID_chain_set)
    cadscore = property(_cadscorelt_python.ChainScore_cadscore_get, _cadscorelt_python.ChainScore_cadscore_set)
    F1_of_areas = property(_cadscorelt_python.ChainScore_F1_of_areas_get, _cadscorelt_python.ChainScore_F1_of_areas_set)
    target_area = property(_cadscorelt_python.ChainScore_target_area_get, _cadscorelt_python.ChainScore_target_area_set)
    model_area = property(_cadscorelt_python.ChainScore_model_area_get, _cadscorelt_python.ChainScore_model_area_set)
    TP_area = property(_cadscorelt_python.ChainScore_TP_area_get, _cadscorelt_python.ChainScore_TP_area_set)
    FP_area = property(_cadscorelt_python.ChainScore_FP_area_get, _cadscorelt_python.ChainScore_FP_area_set)
    FN_area = property(_cadscorelt_python.ChainScore_FN_area_get, _cadscorelt_python.ChainScore_FN_area_set)

    def __init__(self):
        _cadscorelt_python.ChainScore_swiginit(self, _cadscorelt_python.new_ChainScore())
    __swig_destroy__ = _cadscorelt_python.delete_ChainScore

# Register ChainScore in _cadscorelt_python:
_cadscorelt_python.ChainScore_swigregister(ChainScore)
class AtomAtomScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ID1_chain = property(_cadscorelt_python.AtomAtomScore_ID1_chain_get, _cadscorelt_python.AtomAtomScore_ID1_chain_set)
    ID1_residue_seq_number = property(_cadscorelt_python.AtomAtomScore_ID1_residue_seq_number_get, _cadscorelt_python.AtomAtomScore_ID1_residue_seq_number_set)
    ID1_residue_icode = property(_cadscorelt_python.AtomAtomScore_ID1_residue_icode_get, _cadscorelt_python.AtomAtomScore_ID1_residue_icode_set)
    ID1_atom_name = property(_cadscorelt_python.AtomAtomScore_ID1_atom_name_get, _cadscorelt_python.AtomAtomScore_ID1_atom_name_set)
    ID2_chain = property(_cadscorelt_python.AtomAtomScore_ID2_chain_get, _cadscorelt_python.AtomAtomScore_ID2_chain_set)
    ID2_residue_seq_number = property(_cadscorelt_python.AtomAtomScore_ID2_residue_seq_number_get, _cadscorelt_python.AtomAtomScore_ID2_residue_seq_number_set)
    ID2_residue_icode = property(_cadscorelt_python.AtomAtomScore_ID2_residue_icode_get, _cadscorelt_python.AtomAtomScore_ID2_residue_icode_set)
    ID2_atom_name = property(_cadscorelt_python.AtomAtomScore_ID2_atom_name_get, _cadscorelt_python.AtomAtomScore_ID2_atom_name_set)
    cadscore = property(_cadscorelt_python.AtomAtomScore_cadscore_get, _cadscorelt_python.AtomAtomScore_cadscore_set)
    F1_of_areas = property(_cadscorelt_python.AtomAtomScore_F1_of_areas_get, _cadscorelt_python.AtomAtomScore_F1_of_areas_set)
    target_area = property(_cadscorelt_python.AtomAtomScore_target_area_get, _cadscorelt_python.AtomAtomScore_target_area_set)
    model_area = property(_cadscorelt_python.AtomAtomScore_model_area_get, _cadscorelt_python.AtomAtomScore_model_area_set)
    TP_area = property(_cadscorelt_python.AtomAtomScore_TP_area_get, _cadscorelt_python.AtomAtomScore_TP_area_set)
    FP_area = property(_cadscorelt_python.AtomAtomScore_FP_area_get, _cadscorelt_python.AtomAtomScore_FP_area_set)
    FN_area = property(_cadscorelt_python.AtomAtomScore_FN_area_get, _cadscorelt_python.AtomAtomScore_FN_area_set)

    def __init__(self):
        _cadscorelt_python.AtomAtomScore_swiginit(self, _cadscorelt_python.new_AtomAtomScore())
    __swig_destroy__ = _cadscorelt_python.delete_AtomAtomScore

# Register AtomAtomScore in _cadscorelt_python:
_cadscorelt_python.AtomAtomScore_swigregister(AtomAtomScore)
class ResidueResidueScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ID1_chain = property(_cadscorelt_python.ResidueResidueScore_ID1_chain_get, _cadscorelt_python.ResidueResidueScore_ID1_chain_set)
    ID1_residue_seq_number = property(_cadscorelt_python.ResidueResidueScore_ID1_residue_seq_number_get, _cadscorelt_python.ResidueResidueScore_ID1_residue_seq_number_set)
    ID1_residue_icode = property(_cadscorelt_python.ResidueResidueScore_ID1_residue_icode_get, _cadscorelt_python.ResidueResidueScore_ID1_residue_icode_set)
    ID2_chain = property(_cadscorelt_python.ResidueResidueScore_ID2_chain_get, _cadscorelt_python.ResidueResidueScore_ID2_chain_set)
    ID2_residue_seq_number = property(_cadscorelt_python.ResidueResidueScore_ID2_residue_seq_number_get, _cadscorelt_python.ResidueResidueScore_ID2_residue_seq_number_set)
    ID2_residue_icode = property(_cadscorelt_python.ResidueResidueScore_ID2_residue_icode_get, _cadscorelt_python.ResidueResidueScore_ID2_residue_icode_set)
    cadscore = property(_cadscorelt_python.ResidueResidueScore_cadscore_get, _cadscorelt_python.ResidueResidueScore_cadscore_set)
    F1_of_areas = property(_cadscorelt_python.ResidueResidueScore_F1_of_areas_get, _cadscorelt_python.ResidueResidueScore_F1_of_areas_set)
    target_area = property(_cadscorelt_python.ResidueResidueScore_target_area_get, _cadscorelt_python.ResidueResidueScore_target_area_set)
    model_area = property(_cadscorelt_python.ResidueResidueScore_model_area_get, _cadscorelt_python.ResidueResidueScore_model_area_set)
    TP_area = property(_cadscorelt_python.ResidueResidueScore_TP_area_get, _cadscorelt_python.ResidueResidueScore_TP_area_set)
    FP_area = property(_cadscorelt_python.ResidueResidueScore_FP_area_get, _cadscorelt_python.ResidueResidueScore_FP_area_set)
    FN_area = property(_cadscorelt_python.ResidueResidueScore_FN_area_get, _cadscorelt_python.ResidueResidueScore_FN_area_set)

    def __init__(self):
        _cadscorelt_python.ResidueResidueScore_swiginit(self, _cadscorelt_python.new_ResidueResidueScore())
    __swig_destroy__ = _cadscorelt_python.delete_ResidueResidueScore

# Register ResidueResidueScore in _cadscorelt_python:
_cadscorelt_python.ResidueResidueScore_swigregister(ResidueResidueScore)
class ChainChainScore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ID1_chain = property(_cadscorelt_python.ChainChainScore_ID1_chain_get, _cadscorelt_python.ChainChainScore_ID1_chain_set)
    ID2_chain = property(_cadscorelt_python.ChainChainScore_ID2_chain_get, _cadscorelt_python.ChainChainScore_ID2_chain_set)
    cadscore = property(_cadscorelt_python.ChainChainScore_cadscore_get, _cadscorelt_python.ChainChainScore_cadscore_set)
    F1_of_areas = property(_cadscorelt_python.ChainChainScore_F1_of_areas_get, _cadscorelt_python.ChainChainScore_F1_of_areas_set)
    target_area = property(_cadscorelt_python.ChainChainScore_target_area_get, _cadscorelt_python.ChainChainScore_target_area_set)
    model_area = property(_cadscorelt_python.ChainChainScore_model_area_get, _cadscorelt_python.ChainChainScore_model_area_set)
    TP_area = property(_cadscorelt_python.ChainChainScore_TP_area_get, _cadscorelt_python.ChainChainScore_TP_area_set)
    FP_area = property(_cadscorelt_python.ChainChainScore_FP_area_get, _cadscorelt_python.ChainChainScore_FP_area_set)
    FN_area = property(_cadscorelt_python.ChainChainScore_FN_area_get, _cadscorelt_python.ChainChainScore_FN_area_set)

    def __init__(self):
        _cadscorelt_python.ChainChainScore_swiginit(self, _cadscorelt_python.new_ChainChainScore())
    __swig_destroy__ = _cadscorelt_python.delete_ChainChainScore

# Register ChainChainScore in _cadscorelt_python:
_cadscorelt_python.ChainChainScore_swigregister(ChainChainScore)
class MolecularFileInput(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    input_file_path = property(_cadscorelt_python.MolecularFileInput_input_file_path_get, _cadscorelt_python.MolecularFileInput_input_file_path_set)
    data_blob = property(_cadscorelt_python.MolecularFileInput_data_blob_get, _cadscorelt_python.MolecularFileInput_data_blob_set)
    include_heteroatoms = property(_cadscorelt_python.MolecularFileInput_include_heteroatoms_get, _cadscorelt_python.MolecularFileInput_include_heteroatoms_set)
    read_as_assembly = property(_cadscorelt_python.MolecularFileInput_read_as_assembly_get, _cadscorelt_python.MolecularFileInput_read_as_assembly_set)

    def __init__(self, *args):
        _cadscorelt_python.MolecularFileInput_swiginit(self, _cadscorelt_python.new_MolecularFileInput(*args))
    __swig_destroy__ = _cadscorelt_python.delete_MolecularFileInput

# Register MolecularFileInput in _cadscorelt_python:
_cadscorelt_python.MolecularFileInput_swigregister(MolecularFileInput)
class CADScoreComputerParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    probe = property(_cadscorelt_python.CADScoreComputerParameters_probe_get, _cadscorelt_python.CADScoreComputerParameters_probe_set)
    conflate_atom_names = property(_cadscorelt_python.CADScoreComputerParameters_conflate_atom_names_get, _cadscorelt_python.CADScoreComputerParameters_conflate_atom_names_set)
    remap_chains = property(_cadscorelt_python.CADScoreComputerParameters_remap_chains_get, _cadscorelt_python.CADScoreComputerParameters_remap_chains_set)
    score_atom_atom_contacts = property(_cadscorelt_python.CADScoreComputerParameters_score_atom_atom_contacts_get, _cadscorelt_python.CADScoreComputerParameters_score_atom_atom_contacts_set)
    score_residue_residue_contacts = property(_cadscorelt_python.CADScoreComputerParameters_score_residue_residue_contacts_get, _cadscorelt_python.CADScoreComputerParameters_score_residue_residue_contacts_set)
    score_chain_chain_contacts = property(_cadscorelt_python.CADScoreComputerParameters_score_chain_chain_contacts_get, _cadscorelt_python.CADScoreComputerParameters_score_chain_chain_contacts_set)
    score_atom_sas = property(_cadscorelt_python.CADScoreComputerParameters_score_atom_sas_get, _cadscorelt_python.CADScoreComputerParameters_score_atom_sas_set)
    score_residue_sas = property(_cadscorelt_python.CADScoreComputerParameters_score_residue_sas_get, _cadscorelt_python.CADScoreComputerParameters_score_residue_sas_set)
    score_chain_sas = property(_cadscorelt_python.CADScoreComputerParameters_score_chain_sas_get, _cadscorelt_python.CADScoreComputerParameters_score_chain_sas_set)
    score_atom_sites = property(_cadscorelt_python.CADScoreComputerParameters_score_atom_sites_get, _cadscorelt_python.CADScoreComputerParameters_score_atom_sites_set)
    score_residue_sites = property(_cadscorelt_python.CADScoreComputerParameters_score_residue_sites_get, _cadscorelt_python.CADScoreComputerParameters_score_residue_sites_set)
    score_chain_sites = property(_cadscorelt_python.CADScoreComputerParameters_score_chain_sites_get, _cadscorelt_python.CADScoreComputerParameters_score_chain_sites_set)
    record_local_scores = property(_cadscorelt_python.CADScoreComputerParameters_record_local_scores_get, _cadscorelt_python.CADScoreComputerParameters_record_local_scores_set)
    include_self_to_self_scores = property(_cadscorelt_python.CADScoreComputerParameters_include_self_to_self_scores_get, _cadscorelt_python.CADScoreComputerParameters_include_self_to_self_scores_set)
    restrict_input_atoms = property(_cadscorelt_python.CADScoreComputerParameters_restrict_input_atoms_get, _cadscorelt_python.CADScoreComputerParameters_restrict_input_atoms_set)
    subselect_contacts = property(_cadscorelt_python.CADScoreComputerParameters_subselect_contacts_get, _cadscorelt_python.CADScoreComputerParameters_subselect_contacts_set)
    subselect_atoms = property(_cadscorelt_python.CADScoreComputerParameters_subselect_atoms_get, _cadscorelt_python.CADScoreComputerParameters_subselect_atoms_set)

    def __init__(self):
        _cadscorelt_python.CADScoreComputerParameters_swiginit(self, _cadscorelt_python.new_CADScoreComputerParameters())
    __swig_destroy__ = _cadscorelt_python.delete_CADScoreComputerParameters

# Register CADScoreComputerParameters in _cadscorelt_python:
_cadscorelt_python.CADScoreComputerParameters_swigregister(CADScoreComputerParameters)
class CADScoreComputer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, init_params):
        _cadscorelt_python.CADScoreComputer_swiginit(self, _cadscorelt_python.new_CADScoreComputer(init_params))

    def get_parameters(self):
        return _cadscorelt_python.CADScoreComputer_get_parameters(self)

    def clear_reference_sequences(self):
        return _cadscorelt_python.CADScoreComputer_clear_reference_sequences(self)

    def set_reference_sequences_from_file(self, reference_sequences_file):
        return _cadscorelt_python.CADScoreComputer_set_reference_sequences_from_file(self, reference_sequences_file)

    def set_reference_sequences_from_string(self, reference_sequences_string):
        return _cadscorelt_python.CADScoreComputer_set_reference_sequences_from_string(self, reference_sequences_string)

    def clear_reference_stoichiometry(self):
        return _cadscorelt_python.CADScoreComputer_clear_reference_stoichiometry(self)

    def set_reference_stoichiometry(self, reference_stoichiometry):
        return _cadscorelt_python.CADScoreComputer_set_reference_stoichiometry(self, reference_stoichiometry)

    def add_target_structure_from_file_descriptor(self, input_file_info, name):
        return _cadscorelt_python.CADScoreComputer_add_target_structure_from_file_descriptor(self, input_file_info, name)

    def add_target_structure_from_atoms(self, input_atom_balls, name):
        return _cadscorelt_python.CADScoreComputer_add_target_structure_from_atoms(self, input_atom_balls, name)

    def add_model_structure_from_file_descriptor(self, input_file_info, name):
        return _cadscorelt_python.CADScoreComputer_add_model_structure_from_file_descriptor(self, input_file_info, name)

    def add_model_structure_from_atoms(self, input_atom_balls, name):
        return _cadscorelt_python.CADScoreComputer_add_model_structure_from_atoms(self, input_atom_balls, name)

    def add_structure_from_file_descriptor(self, input_file_info, name):
        return _cadscorelt_python.CADScoreComputer_add_structure_from_file_descriptor(self, input_file_info, name)

    def add_structure_from_atoms(self, input_atom_balls, name):
        return _cadscorelt_python.CADScoreComputer_add_structure_from_atoms(self, input_atom_balls, name)

    def get_structure_descriptor(self, name):
        return _cadscorelt_python.CADScoreComputer_get_structure_descriptor(self, name)

    def get_all_structure_descriptors(self):
        return _cadscorelt_python.CADScoreComputer_get_all_structure_descriptors(self)

    def get_all_cadscores_atom_atom_summarized_globally(self):
        return _cadscorelt_python.CADScoreComputer_get_all_cadscores_atom_atom_summarized_globally(self)

    def get_all_cadscores_residue_residue_summarized_globally(self):
        return _cadscorelt_python.CADScoreComputer_get_all_cadscores_residue_residue_summarized_globally(self)

    def get_all_cadscores_chain_chain_summarized_globally(self):
        return _cadscorelt_python.CADScoreComputer_get_all_cadscores_chain_chain_summarized_globally(self)

    def get_all_cadscores_atom_sas_summarized_globally(self):
        return _cadscorelt_python.CADScoreComputer_get_all_cadscores_atom_sas_summarized_globally(self)

    def get_all_cadscores_residue_sas_summarized_globally(self):
        return _cadscorelt_python.CADScoreComputer_get_all_cadscores_residue_sas_summarized_globally(self)

    def get_all_cadscores_chain_sas_summarized_globally(self):
        return _cadscorelt_python.CADScoreComputer_get_all_cadscores_chain_sas_summarized_globally(self)

    def get_all_cadscores_atom_site_summarized_globally(self):
        return _cadscorelt_python.CADScoreComputer_get_all_cadscores_atom_site_summarized_globally(self)

    def get_all_cadscores_residue_site_summarized_globally(self):
        return _cadscorelt_python.CADScoreComputer_get_all_cadscores_residue_site_summarized_globally(self)

    def get_all_cadscores_chain_site_summarized_globally(self):
        return _cadscorelt_python.CADScoreComputer_get_all_cadscores_chain_site_summarized_globally(self)

    def get_local_cadscores_atom_atom(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_atom(self, target_name, model_name)

    def get_local_cadscores_atom_atom_summarized_per_residue_residue(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_atom_summarized_per_residue_residue(self, target_name, model_name)

    def get_local_cadscores_atom_atom_summarized_per_chain_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_atom_summarized_per_chain_chain(self, target_name, model_name)

    def get_local_cadscores_atom_atom_summarized_per_atom(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_atom_summarized_per_atom(self, target_name, model_name)

    def get_local_cadscores_atom_atom_summarized_per_residue(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_atom_summarized_per_residue(self, target_name, model_name)

    def get_local_cadscores_atom_atom_summarized_per_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_atom_summarized_per_chain(self, target_name, model_name)

    def get_local_cadscores_residue_residue(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_residue_residue(self, target_name, model_name)

    def get_local_cadscores_residue_residue_summarized_per_chain_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_residue_residue_summarized_per_chain_chain(self, target_name, model_name)

    def get_local_cadscores_residue_residue_summarized_per_residue(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_residue_residue_summarized_per_residue(self, target_name, model_name)

    def get_local_cadscores_residue_residue_summarized_per_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_residue_residue_summarized_per_chain(self, target_name, model_name)

    def get_local_cadscores_chain_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_chain_chain(self, target_name, model_name)

    def get_local_cadscores_chain_chain_contact_summarized_per_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_chain_chain_contact_summarized_per_chain(self, target_name, model_name)

    def get_local_cadscores_atom_sas(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_sas(self, target_name, model_name)

    def get_local_cadscores_atom_sas_summarized_per_residue(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_sas_summarized_per_residue(self, target_name, model_name)

    def get_local_cadscores_atom_sas_summarized_per_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_sas_summarized_per_chain(self, target_name, model_name)

    def get_local_cadscores_residue_sas(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_residue_sas(self, target_name, model_name)

    def get_local_cadscores_residue_sas_summarized_per_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_residue_sas_summarized_per_chain(self, target_name, model_name)

    def get_local_cadscores_chain_sas(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_chain_sas(self, target_name, model_name)

    def get_local_cadscores_atom_site(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_site(self, target_name, model_name)

    def get_local_cadscores_atom_site_summarized_per_residue(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_site_summarized_per_residue(self, target_name, model_name)

    def get_local_cadscores_atom_site_summarized_per_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_atom_site_summarized_per_chain(self, target_name, model_name)

    def get_local_cadscores_residue_site(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_residue_site(self, target_name, model_name)

    def get_local_cadscores_residue_site_summarized_per_chain(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_residue_site_summarized_per_chain(self, target_name, model_name)

    def get_local_cadscores_chain_site(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_local_cadscores_chain_site(self, target_name, model_name)

    def get_cadscores_atom_atom_summarized_globally(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_cadscores_atom_atom_summarized_globally(self, target_name, model_name)

    def get_cadscores_residue_residue_summarized_globally(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_cadscores_residue_residue_summarized_globally(self, target_name, model_name)

    def get_cadscores_chain_chain_summarized_globally(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_cadscores_chain_chain_summarized_globally(self, target_name, model_name)

    def get_cadscores_atom_sas_summarized_globally(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_cadscores_atom_sas_summarized_globally(self, target_name, model_name)

    def get_cadscores_residue_sas_summarized_globally(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_cadscores_residue_sas_summarized_globally(self, target_name, model_name)

    def get_cadscores_chain_sas_summarized_globally(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_cadscores_chain_sas_summarized_globally(self, target_name, model_name)

    def get_cadscores_atom_site_summarized_globally(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_cadscores_atom_site_summarized_globally(self, target_name, model_name)

    def get_cadscores_residue_site_summarized_globally(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_cadscores_residue_site_summarized_globally(self, target_name, model_name)

    def get_cadscores_chain_site_summarized_globally(self, target_name, model_name):
        return _cadscorelt_python.CADScoreComputer_get_cadscores_chain_site_summarized_globally(self, target_name, model_name)
    __swig_destroy__ = _cadscorelt_python.delete_CADScoreComputer

# Register CADScoreComputer in _cadscorelt_python:
_cadscorelt_python.CADScoreComputer_swigregister(CADScoreComputer)

def enable_considering_residue_names():
    return _cadscorelt_python.enable_considering_residue_names()

def disable_considering_residue_names():
    return _cadscorelt_python.disable_considering_residue_names()

def enable_binarizing_areas():
    return _cadscorelt_python.enable_binarizing_areas()

def disable_binarizing_areas():
    return _cadscorelt_python.disable_binarizing_areas()

def reset_atom_names_conflation_rules():
    return _cadscorelt_python.reset_atom_names_conflation_rules()

def add_atom_names_conflation_rule(residue_name, atom_name, conflated_atom_name):
    return _cadscorelt_python.add_atom_names_conflation_rule(residue_name, atom_name, conflated_atom_name)

def add_atom_names_conflation_rules_from_file(configuration_file_path):
    return _cadscorelt_python.add_atom_names_conflation_rules_from_file(configuration_file_path)

def reset_molecular_radii_assignment_rules():
    return _cadscorelt_python.reset_molecular_radii_assignment_rules()

def configure_molecular_radii_assignment_rules(configuration_file_path):
    return _cadscorelt_python.configure_molecular_radii_assignment_rules(configuration_file_path)

