#!/bin/bash

SCRIPT_DIR=$(dirname $0)

FIRST_GAUGE=$1
SECOND_GAUGE=$2
TEST_SUBJECT=$3
COMPARER=$4
WORKING_DIR=$5
PDB_FILE=$6

#$SCRIPT_DIR/run_first_gauge.bash $FIRST_GAUGE $WORKING_DIR $PDB_FILE
#$SCRIPT_DIR/run_second_gauge.bash $SECOND_GAUGE $WORKING_DIR $PDB_FILE
$SCRIPT_DIR/run_test_subject.bash $TEST_SUBJECT $WORKING_DIR $PDB_FILE
$SCRIPT_DIR/run_comparer.bash $COMPARER $WORKING_DIR $PDB_FILE
$SCRIPT_DIR/run_summarizer.bash $WORKING_DIR $PDB_FILE
