#!/bin/bash

SCRIPT_DIR=$(dirname $0)

FIRST_GAUGE=$1
SECOND_GAUGE=$2
TEST_SUBJECT=$3
COMPARER=$4
EPSILON=$5
WORKING_DIR=$6
PDB_FILE=$7

$SCRIPT_DIR/run_first_gauge.bash $FIRST_GAUGE $WORKING_DIR $PDB_FILE
$SCRIPT_DIR/run_second_gauge.bash $SECOND_GAUGE $WORKING_DIR $PDB_FILE
$SCRIPT_DIR/run_test_subject.bash $TEST_SUBJECT $EPSILON $WORKING_DIR $PDB_FILE
$SCRIPT_DIR/run_comparer.bash $COMPARER $EPSILON $WORKING_DIR $PDB_FILE
$SCRIPT_DIR/run_summarizer.bash $WORKING_DIR $PDB_FILE
