#!/bin/bash

COMPARER=$1
EPSILON=$2
WORKING_DIR=$3
PDB_FILE=$4

PDB_FILE_BASENAME=$(basename $PDB_FILE .ent.gz)
PDB_FILE_DOMAIN=$(echo $PDB_FILE_BASENAME | sed 's/pdb.\(..\)./\1/')
WORKING_DIR="$WORKING_DIR/$PDB_FILE_DOMAIN"

BALLS_FILE="$WORKING_DIR/$PDB_FILE_BASENAME.first_gauge.balls"
FIRST_GAUGE_QUADRUPLES_FILE="$WORKING_DIR/$PDB_FILE_BASENAME.first_gauge.quadruples"
SECOND_GAUGE_QUADRUPLES_FILE="$WORKING_DIR/$PDB_FILE_BASENAME.second_gauge.quadruples"
TEST_SUBJECT_QUADRUPLES_FILE="$WORKING_DIR/$PDB_FILE_BASENAME.test_subject.quadruples"

gunzip -f $BALLS_FILE.gz $FIRST_GAUGE_QUADRUPLES_FILE.gz $SECOND_GAUGE_QUADRUPLES_FILE.gz $TEST_SUBJECT_QUADRUPLES_FILE.gz &> /dev/null

if [ -s "$BALLS_FILE" ] && [ -s "$FIRST_GAUGE_QUADRUPLES_FILE" ] && [ -s "$TEST_SUBJECT_QUADRUPLES_FILE" ]
then
	FIRST_RESULTS_FILE="$WORKING_DIR/$PDB_FILE_BASENAME.comparison.first"
	$COMPARER --mode compare-quadruples-sets --epsilon $EPSILON --first-quadruples-file $FIRST_GAUGE_QUADRUPLES_FILE --second-quadruples-file $TEST_SUBJECT_QUADRUPLES_FILE < $BALLS_FILE > $FIRST_RESULTS_FILE	
fi

if [ -s "$BALLS_FILE" ] && [ -s "$SECOND_GAUGE_QUADRUPLES_FILE" ] && [ -s "$TEST_SUBJECT_QUADRUPLES_FILE" ]
then
	SECOND_RESULTS_FILE="$WORKING_DIR/$PDB_FILE_BASENAME.comparison.second"
	$COMPARER --mode compare-quadruples-sets --epsilon $EPSILON --first-quadruples-file $SECOND_GAUGE_QUADRUPLES_FILE --second-quadruples-file $TEST_SUBJECT_QUADRUPLES_FILE < $BALLS_FILE > $SECOND_RESULTS_FILE	
fi
	
gzip -f $BALLS_FILE $FIRST_GAUGE_QUADRUPLES_FILE $SECOND_GAUGE_QUADRUPLES_FILE $TEST_SUBJECT_QUADRUPLES_FILE &> /dev/null
