#!/bin/bash

readonly ZEROARG=$0
OUTDIR="$1"
INLIST="$2"
INMODE="$3"

if [ -z "$INLIST" ] || [ -z "$OUTDIR" ]
then
	echo >&2 "Error: missing arguments"
	exit 1
fi

if [ "$INMODE" == "single" ]
then
	TMPLIST=$(mktemp)
	echo "$INLIST" > "$TMPLIST"
	$0 "$OUTDIR" "$TMPLIST"
	rm "$TMPLIST"
	exit 0
fi

if [ ! -s "$INLIST" ]
then
	echo >&2 "Error: invalid list file '$INLIST'"
	exit 1
fi

FIRSTFILE="$(head -1 "$INLIST")"

if [ -z "$FIRSTFILE" ] || [ ! -s "$FIRSTFILE" ]
then
	echo >&2 "Error: invalid first file '$FIRSTFILE'"
	exit 1
fi

if [[ "$ZEROARG" == *"/"* ]]
then
	cd $(dirname $ZEROARG)
	export PATH=$(pwd):$PATH
	cd - &> /dev/null
fi

command -v voronota-voromqa-with-hull-blurring &> /dev/null || { echo >&2 "Error: 'voronota-voromqa-with-hull-blurring' executable not in binaries path"; exit 1; }

mkdir -p "$OUTDIR/singles"

if [ ! -d "$OUTDIR/singles" ]
then
	echo >&2 "Error: could not create output directory"
	exit 1
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

cat "$INLIST" | while read INFILE
do
	if [ ! -s "$OUTDIR/singles/$(basename $INFILE)/hbo_residue_profile" ]
	then
		voronota-voromqa-with-hull-blurring \
		  --cache-dir "$OUTDIR/cache" \
		  --input "$INFILE" \
		  --hull-blurring-reference "$FIRSTFILE" \
		  --hull-blurring-depth 3 \
		  --hull-blurring-output "$OUTDIR/singles/$(basename $INFILE)/hbo"
	fi
done

cat "$OUTDIR/singles/$(basename $FIRSTFILE)/hbo_residue_profile" | awk '{print $1 " " $2 " " $3 " 0 0"}' > "$TMPLDIR/accumulation"

cat "$INLIST" | while read INFILE
do
	paste "$TMPLDIR/accumulation" <(cat "$OUTDIR/singles/$(basename $INFILE)/hbo_residue_profile" | awk '{print $4}') \
	| awk '{print $1 " " $2 " " $3 " " ($4+1) " " ($5+$6)}' \
	> "$TMPLDIR/accumulation_update"
	mv "$TMPLDIR/accumulation_update" "$TMPLDIR/accumulation"
done

cat "$TMPLDIR/accumulation" \
| awk '{print $1 " " $2 " " $3 " " ($5/$4)}' \
> "$OUTDIR/hbo_residue_profile_consensus"


R --vanilla --args "$OUTDIR/hbo_residue_profile_consensus" "$OUTDIR/hbo_residue_profile_consensus_" &> /dev/null << 'EOF'

args=commandArgs(TRUE);
infile=args[1];
output_prefix=args[2];
t=read.table(infile, header=FALSE, stringsAsFactors=FALSE);
v=t$V4;
centers=sort(kmeans(x=v, centers=2, iter.max=100)$centers[,1]);
split=mean(centers[1:2]);

s=(pnorm((v-split)*qnorm(0.75)/(centers[2]-split)));
t$V4=s;
write.table(t, paste(output_prefix, "probabilities", sep=""), quote=FALSE, row.names=FALSE, col.names=FALSE);

png(filename=paste(output_prefix, "energies_to_probabilities.png", sep=""), width=5, height=5, units="in", res=200);
plot(v, s, ylim=c(0, 1), xlab="Normalized energy", ylab="Interface probability");
lines(c(split, split), c(0, 1), col="red");
lines(c(min(v), max(v)), c(0.5, 0.5), col="red");
dev.off();

d0=density(v);
d1=density(v[which(v<split)]);
d2=density(v[which(v>split)]);
d_y_max=max(c(d0$y, d1$y, d2$y));

png(filename=paste(output_prefix, "density.png", sep=""), width=5, height=5, units="in", res=200);
plot(d0, ylim=c(0, d_y_max), xlab="Normalized energy", main="Histogram of normalized energy");
lines(d1$x, d1$y, col="blue");
lines(d2$x, d2$y, col="green");
lines(c(split, split), c(0, d_y_max), col="red");
lines(c(centers[1], centers[1]), c(0, d_y_max), col="blue");
lines(c(centers[2], centers[2]), c(0, d_y_max), col="green");
dev.off();

png(filename=paste(output_prefix, "wave_of_energies.png", sep=""), width=15, height=5, units="in", res=200);
plot(v, ylab="Normalized energy", type="l");
lines(c(1, length(v)), c(split, split), col="red");
dev.off();

png(filename=paste(output_prefix, "wave_of_probabilities.png", sep=""), width=15, height=5, units="in", res=200);
plot(s, ylab="Interface probability", type="l");
lines(c(1, length(s)), c(0.5, 0.5), col="red");
dev.off();

EOF


cat "$OUTDIR/hbo_residue_profile_consensus_probabilities" \
| awk '{print "c<" $1 ">r<" $2 ">R<" $3 "> " $4}' \
| sed 's/c<\.>//' \
> "$TMPLDIR/consensus_adjuncts"

cat "$INLIST" | head -1 | while read INFILE
do
	cat "$INFILE" \
	| voronota get-balls-from-atoms-file \
	  --annotated \
	| voronota query-balls \
	  --match 'R<LEU,ALA,GLY,VAL,GLU,SER,LYS,ILE,ASP,THR,ARG,PRO,ASN,PHE,GLN,TYR,HIS,MET,TRP,CYS,MSE,SEC>' \
	| voronota query-balls \
	  --drop-adjuncts \
	  --drop-altloc-indicators \
	| voronota query-balls \
	  --set-adjuncts 'score=0' \
	  --set-external-adjuncts "$TMPLDIR/consensus_adjuncts" \
	  --set-external-adjuncts-name score \
	| voronota x-write-balls-to-atoms-file \
	  --pdb-output "$OUTDIR/singles/$(basename $INFILE)/hbo_residue_profile_consensus.pdb" \
	  --pdb-output-b-factor score \
	> /dev/null
done

cp "$OUTDIR/singles/$(basename $FIRSTFILE)/hbo_residue_profile_consensus.pdb" "$OUTDIR/hbo_residue_profile_consensus.pdb"

cat > "$OUTDIR/show_colored_surface.pml" << 'EOF'
hide all
show surface
spectrum b, blue_white_red, all, 0.25, 0.75
zoom
EOF
