#!/bin/bash

readonly ZEROARG="$0"
INFILE=""
REBUILD_SIDECHAINS_COMMAND=""
OUTFILE_TABLE=""
HELP_MODE=false

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	-i|--input)
		INFILE="$OPTARG"
		shift
		;;
	--rebuild-sidechains)
		REBUILD_SIDECHAINS_COMMAND="$OPTARG"
		shift
		;;
	--output-table)
		OUTFILE_TABLE="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE=true
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ -z "$INFILE" ] || $HELP_MODE
then
cat >&2 << EOF

Options:
    --input | -i                   string   *  input structure file in PDB format
    --output-table                 string      output table file
    --help | -h                                flag to display help message and exit

EOF
exit 1
fi

if [ -z "$INFILE" ] && [ ! -s "$INFILE" ]
then
	echo >&2 "Error: missing input file"
	exit 1
fi

if [[ "$ZEROARG" == *"/"* ]]
then
	cd $(dirname $ZEROARG)
	export PATH=$(pwd):$PATH
	cd - &> /dev/null
fi

command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
command -v voronota-voromqa &> /dev/null || { echo >&2 "Error: 'voronota-voromqa' executable not in binaries path"; exit 1; }

if [ -n "$REBUILD_SIDECHAINS_COMMAND" ]
then
	command -v $REBUILD_SIDECHAINS_COMMAND &> /dev/null || { echo >&2 "Error: '$REBUILD_SIDECHAINS_COMMAND' command, requested for rebuilding side-chains, is not available"; exit 1; }
fi

ADDITIONAL_VOROMQA_OPTIONS=()
if [ -n "$REBUILD_SIDECHAINS_COMMAND" ]
then
	ADDITIONAL_VOROMQA_OPTIONS=("--rebuild-sidechains" "$REBUILD_SIDECHAINS_COMMAND")
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

cat "$INFILE" \
| voronota get-balls-from-atoms-file --annotated \
| tee "$TMPLDIR/balls" \
| voronota expand-descriptors \
| awk '{print $1}' \
| sort \
| uniq \
> "$TMPLDIR/chains"

if [ "$(cat $TMPLDIR/chains | wc -l)" != 2 ]
then
	echo >&2 "Error: input file does not contain exactly two chains"
	exit 1
fi

cat "$TMPLDIR/balls" \
| voronota query-balls-clashes \
  --clash-distance 6.0 \
| awk '{print $1 " " $2 " 1 " $3 " . ."}' \
| voronota query-contacts \
  --no-same-chain \
| wc -l \
> "$TMPLDIR/touching_magnitude"

if [ "$(cat $TMPLDIR/touching_magnitude)" -eq "0" ]
then
	echo >&2 "Error: chains are not in contact"
	exit 1
fi

cat "$TMPLDIR/balls" \
| voronota query-balls-clashes \
  --clash-distance 3.0 \
| awk '{print $1 " " $2 " 1 " $3 " . ."}' \
| voronota query-contacts \
  --match-first 'A<C,CA,CB,CD,CD1,CD2,CE,CE1,CE2,CE3,CG,CG1,CG2,CH2,CZ,CZ2,CZ3>' \
  --no-same-chain \
> "$TMPLDIR/clashes"

echo $(cat $TMPLDIR/clashes | wc -l) $(cat $TMPLDIR/clashes | awk '{print $1 " " $2}' | tr ' ' '\n' | sort | uniq | wc -l) \
> "$TMPLDIR/clashes_summary"

cat "$TMPLDIR/balls" \
| voronota write-balls-to-atoms-file --pdb-output "$TMPLDIR/atoms.pdb" \
> /dev/null

cat "$TMPLDIR/balls" \
| voronota query-balls --match "c<$(head -1 $TMPLDIR/chains)>" \
| voronota write-balls-to-atoms-file --pdb-output "$TMPLDIR/atoms1.pdb" \
> "$TMPLDIR/balls1"

cat "$TMPLDIR/balls" \
| voronota query-balls --match "c<$(tail -1 $TMPLDIR/chains)>" \
| voronota write-balls-to-atoms-file --pdb-output "$TMPLDIR/atoms2.pdb" \
> "$TMPLDIR/balls2"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms.pdb" \
  --contacts-query '--no-same-chain --no-solvent' \
  --output-selected-scores "$TMPLDIR/voromqa_results_iface_local" \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_iface_global"

cat "$TMPLDIR/voromqa_results_iface_local" \
| voronota expand-descriptors \
| awk '{print "c<" $1 ">r<" $2 ">i<" $3 ">R<" $6 ">A<" $7 ">"}' \
| sed 's/i<\.>//' \
> "$TMPLDIR/iface_selection"

cat "$TMPLDIR/iface_selection" \
| grep "c<$(head -1 $TMPLDIR/chains)>" \
> "$TMPLDIR/iface_selection1"

cat "$TMPLDIR/iface_selection" \
| grep "c<$(tail -1 $TMPLDIR/chains)>" \
> "$TMPLDIR/iface_selection2"

echo $(cat "$TMPLDIR/iface_selection1" | wc -l) $(cat "$TMPLDIR/iface_selection2" | wc -l) \
> "$TMPLDIR/selection_summary"

if [ "$(cat $TMPLDIR/selection_summary | awk '{print ($1+$2)}')" -eq "0" ]
then
	echo >&2 "Error: chains are not in contact"
	exit 1
fi

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms1.pdb" \
  --contacts-query "--match-external-first $TMPLDIR/iface_selection1 --match-second c<solvent>" \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_iface_global1"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms2.pdb" \
  --contacts-query "--match-external-first $TMPLDIR/iface_selection2 --match-second c<solvent>" \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_iface_global2"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms.pdb" \
  --contacts-query '--match-second c<solvent>' \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_sas_global"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms1.pdb" \
  --contacts-query '--match-second c<solvent>' \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_sas_global1"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms2.pdb" \
  --contacts-query '--match-second c<solvent>' \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_sas_global2"

{
	echo    input                    $INFILE
	
	echo    clashes                  $(cat $TMPLDIR/clashes_summary | awk '{print $1}')
	echo    clashed_atoms            $(cat $TMPLDIR/clashes_summary | awk '{print $2}')
	
	echo    iface_atoms1             $(cat $TMPLDIR/selection_summary | awk '{print $1}')
	echo    iface_atoms2             $(cat $TMPLDIR/selection_summary | awk '{print $2}')
	
	echo    full_voromqa             $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $2}')
	echo    full_residues            $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $3}')
	echo    full_atoms               $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $4}')
	echo    full_iface_voromqa       $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $5}')
	echo    full_iface_atoms         $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $6}')
	echo    full_iface_contacts      $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $7}')
	echo    full_iface_area          $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $8}')
	echo    full_iface_xarea         $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $9}')
	echo    full_iface_energy        $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $10}')
	echo    full_iface_norm_energy   $(cat $TMPLDIR/voromqa_results_iface_global | awk '{print $11}')
	echo    full_sas_voromqa         $(cat $TMPLDIR/voromqa_results_sas_global | awk '{print $5}')
	echo    full_sas_contacts        $(cat $TMPLDIR/voromqa_results_sas_global | awk '{print $7}')
	echo    full_sas_area            $(cat $TMPLDIR/voromqa_results_sas_global | awk '{print $8}')
	echo    full_sas_xarea           $(cat $TMPLDIR/voromqa_results_sas_global | awk '{print $9}')
	echo    full_sas_energy          $(cat $TMPLDIR/voromqa_results_sas_global | awk '{print $10}')
	echo    full_sas_norm_energy     $(cat $TMPLDIR/voromqa_results_sas_global | awk '{print $11}')
	
	echo    chain1_voromqa           $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $2}')
	echo    chain1_residues          $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $3}')
	echo    chain1_atoms             $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $4}')
	echo    chain1_iface_voromqa     $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $5}')
	echo    chain1_iface_atoms       $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $6}')
	echo    chain1_iface_contacts    $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $7}')
	echo    chain1_iface_area        $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $8}')
	echo    chain1_iface_xarea       $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $9}')
	echo    chain1_iface_energy      $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $10}')
	echo    chain1_iface_norm_energy $(cat $TMPLDIR/voromqa_results_iface_global1 | awk '{print $11}')
	echo    chain1_sas_voromqa       $(cat $TMPLDIR/voromqa_results_sas_global1 | awk '{print $5}')
	echo    chain1_sas_contacts      $(cat $TMPLDIR/voromqa_results_sas_global1 | awk '{print $7}')
	echo    chain1_sas_area          $(cat $TMPLDIR/voromqa_results_sas_global1 | awk '{print $8}')
	echo    chain1_sas_xarea         $(cat $TMPLDIR/voromqa_results_sas_global1 | awk '{print $9}')
	echo    chain1_sas_energy        $(cat $TMPLDIR/voromqa_results_sas_global1 | awk '{print $10}')
	echo    chain1_sas_norm_energy   $(cat $TMPLDIR/voromqa_results_sas_global1 | awk '{print $11}')
	
	echo    chain2_voromqa           $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $2}')
	echo    chain2_residues          $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $3}')
	echo    chain2_atoms             $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $4}')
	echo    chain2_iface_voromqa     $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $5}')
	echo    chain2_iface_atoms       $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $6}')
	echo    chain2_iface_contacts    $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $7}')
	echo    chain2_iface_area        $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $8}')
	echo    chain2_iface_xarea       $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $9}')
	echo    chain2_iface_energy      $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $10}')
	echo    chain2_iface_norm_energy $(cat $TMPLDIR/voromqa_results_iface_global2 | awk '{print $11}')
	echo    chain2_sas_voromqa       $(cat $TMPLDIR/voromqa_results_sas_global2 | awk '{print $5}')
	echo    chain2_sas_contacts      $(cat $TMPLDIR/voromqa_results_sas_global2 | awk '{print $7}')
	echo    chain2_sas_area          $(cat $TMPLDIR/voromqa_results_sas_global2 | awk '{print $8}')
	echo    chain2_sas_xarea         $(cat $TMPLDIR/voromqa_results_sas_global2 | awk '{print $9}')
	echo    chain2_sas_energy        $(cat $TMPLDIR/voromqa_results_sas_global2 | awk '{print $10}')
	echo    chain2_sas_norm_energy   $(cat $TMPLDIR/voromqa_results_sas_global2 | awk '{print $11}')
	
} \
| sed 's/^\(.*\)$/\1 0/' \
| awk '{print $1 " " $2}' \
> "$TMPLDIR/result"

if [ -n "$OUTFILE_TABLE" ]
then
	{
		cat $TMPLDIR/result | awk '{print $1}' | tr '\n' ' '
		echo
		cat $TMPLDIR/result | awk '{print $2}' | tr '\n' ' '
		echo
	} | column -t > "$OUTFILE_TABLE"
fi

cat "$TMPLDIR/result" | column -t
