#!/bin/bash

readonly ZEROARG="$0"
INFILE=""
REBUILD_SIDECHAINS_COMMAND=""
HELP_MODE=false

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	-i|--input)
		INFILE="$OPTARG"
		shift
		;;
	--rebuild-sidechains)
		REBUILD_SIDECHAINS_COMMAND="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE=true
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ -z "$INFILE" ] || $HELP_MODE
then
cat >&2 << EOF

Options:
    --input | -i                   string   *  input structure file in PDB format
    --help | -h                                flag to display help message and exit

EOF
exit 1
fi

if [ -z "$INFILE" ] && [ ! -s "$INFILE" ]
then
	echo >&2 "Error: missing input file"
	exit 1
fi

if [[ "$ZEROARG" == *"/"* ]]
then
	cd $(dirname $ZEROARG)
	export PATH=$(pwd):$PATH
	cd - &> /dev/null
fi

command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
command -v voronota-voromqa &> /dev/null || { echo >&2 "Error: 'voronota-voromqa' executable not in binaries path"; exit 1; }

if [ -n "$REBUILD_SIDECHAINS_COMMAND" ]
then
	command -v $REBUILD_SIDECHAINS_COMMAND &> /dev/null || { echo >&2 "Error: '$REBUILD_SIDECHAINS_COMMAND' command, requested for rebuilding side-chains, is not available"; exit 1; }
fi

ADDITIONAL_VOROMQA_OPTIONS=()
if [ -n "$REBUILD_SIDECHAINS_COMMAND" ]
then
	ADDITIONAL_VOROMQA_OPTIONS=("--rebuild-sidechains" "$REBUILD_SIDECHAINS_COMMAND")
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

cat "$INFILE" \
| voronota get-balls-from-atoms-file --annotated \
| tee "$TMPLDIR/balls" \
| voronota x-expand-descriptors \
| awk '{print $1}' \
| sort \
| uniq \
> "$TMPLDIR/chains"

if [ "$(cat $TMPLDIR/chains | wc -l)" != 2 ]
then
	echo >&2 "Error: input file does not contain exactly two chains"
	exit 1
fi

cat "$TMPLDIR/balls" \
| voronota x-query-balls-clashes \
  --clash-distance 3.0 \
| awk '{print $1 " " $2 " 1 " $3 " . ."}' \
| voronota query-contacts \
  --match-first 'A<C,CA,CB,CD,CD1,CD2,CE,CE1,CE2,CE3,CG,CG1,CG2,CH2,CZ,CZ2,CZ3>' \
  --no-same-chain \
> "$TMPLDIR/clashes"

echo $(cat $TMPLDIR/clashes | wc -l) $(cat $TMPLDIR/clashes | awk '{print $1 " " $2}' | tr ' ' '\n' | sort | uniq | wc -l) \
> "$TMPLDIR/clashes_summary"

cat "$TMPLDIR/balls" \
| voronota x-write-balls-to-atoms-file --pdb-output "$TMPLDIR/atoms.pdb" \
> /dev/null

cat "$TMPLDIR/balls" \
| voronota query-balls --match "c<$(head -1 $TMPLDIR/chains)>" \
| voronota x-write-balls-to-atoms-file --pdb-output "$TMPLDIR/atoms1.pdb" \
> "$TMPLDIR/balls1"

cat "$TMPLDIR/balls" \
| voronota query-balls --match "c<$(tail -1 $TMPLDIR/chains)>" \
| voronota x-write-balls-to-atoms-file --pdb-output "$TMPLDIR/atoms2.pdb" \
> "$TMPLDIR/balls2"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms.pdb" \
  --contacts-query '--no-same-chain --no-solvent' \
  --output-selected-scores "$TMPLDIR/voromqa_results_iface_local" \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_iface_global"

cat "$TMPLDIR/voromqa_results_iface_local" \
| voronota x-expand-descriptors \
| awk '{print "c<" $1 ">r<" $2 ">i<" $3 ">R<" $6 ">A<" $7 ">"}' \
| sed 's/i<\.>//' \
> "$TMPLDIR/iface_selection"

cat "$TMPLDIR/iface_selection" \
| grep "c<$(head -1 $TMPLDIR/chains)>" \
> "$TMPLDIR/iface_selection1"

cat "$TMPLDIR/iface_selection" \
| grep "c<$(tail -1 $TMPLDIR/chains)>" \
> "$TMPLDIR/iface_selection2"

echo $(cat "$TMPLDIR/iface_selection1" | wc -l) $(cat "$TMPLDIR/iface_selection2" | wc -l) \
> "$TMPLDIR/selection_summary"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms1.pdb" \
  --contacts-query "--match-external-first $TMPLDIR/iface_selection1 --match-second c<solvent>" \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_iface_global1"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms2.pdb" \
  --contacts-query "--match-external-first $TMPLDIR/iface_selection2 --match-second c<solvent>" \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_iface_global2"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms.pdb" \
  --contacts-query '--match-second c<solvent>' \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_sas_global"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms1.pdb" \
  --contacts-query '--match-second c<solvent>' \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_sas_global1"

voronota-voromqa "${ADDITIONAL_VOROMQA_OPTIONS[@]}" \
  --cache-dir "$TMPLDIR/cache" \
  --input "$TMPLDIR/atoms2.pdb" \
  --contacts-query '--match-second c<solvent>' \
  --print-energy-of-contacts-selection \
> "$TMPLDIR/voromqa_results_sas_global2"

cat "$TMPLDIR/clashes_summary"
cat "$TMPLDIR/selection_summary"

for FNAME in $TMPLDIR/voromqa_results_*_global*
do
	echo $FNAME
	cat $FNAME
done | column -t
