#ifndef DEPENDENCIES_LINENOISE_USE_LINENOISE_H_
#define DEPENDENCIES_LINENOISE_USE_LINENOISE_H_

#ifndef USE_LINENOISE
#define USE_LINENOISE 1
#endif

#endif /* DEPENDENCIES_LINENOISE_USE_LINENOISE_H_ */
